database:
  host: localhost
  port: 5432
  user: test_user
  password: test_password
  name: test
  sslmode: disable
  migrations: internal/migrations

nats:
  cluster_id: test-cluster
  client_id: consumer
  channel: session

http_server:
  ip: localhost
  port: 8080