version: "3.9"
services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  docker-gs-ping:
    build: .
    ports:
      - "8080:8080"
  NATS-streaming:
    image: "nats-streaming:0.24-alpine"
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres:

networks:
  L0:
    driver: bridge