version: "3.9"
services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5432:5432"
  NATS-streaming:
    image: "nats-streaming:0.24-alpine"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

volumes:
  postgres:

networks:
  L0:
    driver: bridge